---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:
    - name: Installing Linux Apps
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - make
          - curl
          - wget
          - apt-transport-https
          - ca-certificates
          - gnupg
          - python3-pip
          - git
          - bash-completion
#          - gnupg-agent
          - zsh
#          - flameshot
#          - fonts-hack
#          - tilix
#          - virtualbox
#          - mlocate
#          - mtr
#          - zlib1g-dev
#          - clang
          - vim
          - tmux       
    - block:
      - name: Verify if Oh-My-zsh is installed
        command: test -d /home/{{ ansible_user_id }}/.oh-my-zsh
        register: ohmyzsh
        ignore_errors: true
      - name: Installing Oh-My-zsh
        shell:
          cmd: 'curl -fsL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash'
          warn: false
        when: ohmyzsh.rc != 0
      - name: Changing Default Shell to ZSH
        become: yes
        user: 
          name: '{{ ansible_user_id }}'
          shell: /bin/zsh 
      - name: Changing Default ZSH Theme to Agnoster
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          regexp: '^ZSH_THEME='
          line: 'ZSH_THEME="agnoster"'
      - name: Creating ZSH Completion folder
        file:
          path: /home/{{ ansible_user_id }}/.oh-my-zsh/completions
          state: directory
          mode: 0755
      - name: Adding autoload to compinit
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          line: 'autoload -U compinit && compinit'
          state: present

    - block:
      - name: Install asdf
        git:
          dest: ~/.asdf
          repo: "https://github.com/asdf-vm/asdf.git"
          accept_hostkey: yes
          update: no
        when: ansible_os_family == "Debian"
      # zsh
      - name: add asdf to zsh
        lineinfile:
          path: ~/.zshrc
          line: . $HOME/.asdf/asdf.sh
        when: ansible_os_family == "Debian"
        
      - name: add asdf-completions to zsh
        lineinfile:
          path: ~/.zshrc
          line: . $HOME/.asdf/completions/asdf.bash
        when: ansible_os_family == "Debian"
      # bashrc
      - name: add asdf to bashrc
        lineinfile:
          path: ~/.bashrc
          line: . $HOME/.asdf/asdf.sh
        when: ansible_os_family == "Debian"

      - name: add asdf-completions to bashrc
        lineinfile:
          path: ~/.bashrc
          line: . $HOME/.asdf/completions/asdf.bash
        when: ansible_os_family == "Debian"

      - name: asdf add plugins
        shell: |
          asdf plugin add yq
          asdf install yq latest
          asdf global yq latest
          yq --version
          
          

